// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416100803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$8lxccSmzuJXmquxaX2YHmuDq8gKqKdfNt97LB7jBGT2bB2FvRQfG2",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$XcbftHSmdlcfJ.0YqfOZy.AylEwEDpKhjHa1DOTdFq.5FzPVaMOZ6",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.menon@xyz.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Menon",
                            Phone = "9876543210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Analyst",
                            Email = "arjun.sharma@xyz.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9876543211",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "neha.kapoor@xyz.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9876543212",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "rohan.iyer@xyz.com",
                            FirstName = "Rohan",
                            JoinDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Iyer",
                            Phone = "9876543213",
                            Salary = 710000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Coordinator",
                            Email = "sneha.rao@xyz.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rao",
                            Phone = "9876543214",
                            Salary = 590000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "kiran.patel@xyz.com",
                            FirstName = "Kiran",
                            JoinDate = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Patel",
                            Phone = "9876543215",
                            Salary = 700000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "meera.joshi@xyz.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9876543216",
                            Salary = 640000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Acquisition Specialist",
                            Email = "amit.verma@xyz.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Verma",
                            Phone = "9876543217",
                            Salary = 610000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "divya.nair@xyz.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2021, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nair",
                            Phone = "9876543218",
                            Salary = 660000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Lead",
                            Email = "vikram.singh@xyz.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Singh",
                            Phone = "9876543219",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "UI Developer",
                            Email = "ananya.das@xyz.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Das",
                            Phone = "9876543220",
                            Salary = 730000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "SEO Specialist",
                            Email = "rahul.kulkarni@xyz.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kulkarni",
                            Phone = "9876543221",
                            Salary = 605000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "pooja.bhat@xyz.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Bhat",
                            Phone = "9876543222",
                            Salary = 780000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Finance Manager",
                            Email = "sanjay.gupta@xyz.com",
                            FirstName = "Sanjay",
                            JoinDate = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Gupta",
                            Phone = "9876543223",
                            Salary = 810000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "lavanya.krishnan@xyz.com",
                            FirstName = "Lavanya",
                            JoinDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Krishnan",
                            Phone = "9876543224",
                            Salary = 790000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
